# Generated by Django 4.0.2 on 2022-02-23 23:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 23, 23, 12, 51, 49484)),
        ),
        migrations.AddField(
            model_name='complaint',
            name='state',
            field=models.CharField(choices=[('open', 'Open'), ('reimbursed', 'Reimbursed'), ('closed', 'Closed')], default='open', max_length=30),
        ),
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
