# Generated by Django 4.0.2 on 2022-02-23 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_create_date_complaint_state_complaint_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
