# Generated by Django 4.0.2 on 2022-03-22 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Mow Lawn', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_estimate', models.IntegerField()),
                ('zip_code', models.CharField(max_length=10)),
                ('complete', models.BooleanField(default=False)),
                ('completion_window_start', models.DateField()),
                ('completion_window_end', models.DateField()),
                ('accepted_bid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_bid', to='jobs.bid')),
                ('claimed_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claimed_user', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobtype')),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='selected_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_job', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
