# Generated by Django 3.2.6 on 2022-02-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20220227_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
