# Generated by Django 4.0.2 on 2022-03-15 17:50

from django.db import migrations
from django.contrib.auth.models import Group


def seed_auth_groups(apps, schema_editor):
    worker_group = Group.objects.create(name="Worker")
    customer_group = Group.objects.create(name="Customer")
    owner_group = Group.objects.create(name="Owner")

def remove_auth_groups(apps, schema_editor):
    Group.objects.get(name="Worker").delete()
    Group.objects.get(name="Customer").delete()
    Group.objects.get(name="Owner").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_auth_groups, remove_auth_groups),
    ]
